name: focusable_control_builder
description: Easily create custom controls that respond correctly to mouse and keyboard.
version: 1.0.0-prerelease
homepage: https://github.com/gskinnerTeam/flutter-focusable-control-builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
